/*
 *  Purpose          :    This is interface class showing the discount on purchase.
 *  Created By       :    Shailendra Sharma
 *  Created Date     :    2022/06/29
 *  Revision Logs    :    V_1.0 - Created - 2022/06/29
 */
public interface PurchaseOrder {
     /*
    * Created By    :    Shailendra Sharma
    * Purpose       :    This method has signature only.
    * Params        :    Void
    * Return        :    Void
    */
    Double discount();
}